package database

import "fmt"

// autoIncPK returns the dialect-specific "auto-incrementing integer primary
// key" column definition.
func autoIncPK(d Dialect) string {
	if d == DialectPostgres {
		return "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
	}
	return "INTEGER PRIMARY KEY AUTOINCREMENT"
}

// schema returns the full CREATE TABLE script for the given dialect. TEXT,
// INTEGER (used as 0/1 booleans), and REFERENCES ... ON DELETE ... are
// portable between SQLite and PostgreSQL as-is; only the autoincrement
// primary-key clause differs, so it is templated in.
func schema(d Dialect) string {
	return fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS providers (
    id                TEXT PRIMARY KEY,
    name              TEXT NOT NULL,
    kind              TEXT NOT NULL CHECK (kind IN ('internal','oidc','oauth2')),
    template          TEXT NOT NULL DEFAULT '',
    issuer            TEXT NOT NULL DEFAULT '',
    client_id         TEXT NOT NULL DEFAULT '',
    client_secret_enc TEXT NOT NULL DEFAULT '',
    authorization_url TEXT NOT NULL DEFAULT '',
    access_token_url  TEXT NOT NULL DEFAULT '',
    resource_url      TEXT NOT NULL DEFAULT '',
    logout_url        TEXT NOT NULL DEFAULT '',
    user_identifier   TEXT NOT NULL DEFAULT 'sub',
    scopes            TEXT NOT NULL DEFAULT '',
    redirect_url      TEXT NOT NULL DEFAULT '',
    enabled           INTEGER NOT NULL DEFAULT 1,
    created_at        TEXT NOT NULL,
    updated_at        TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id            %[1]s,
    subject       TEXT NOT NULL UNIQUE,
    username      TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL DEFAULT '',
    email         TEXT NOT NULL DEFAULT '',
    name          TEXT NOT NULL DEFAULT '',
    provider_id   TEXT REFERENCES providers(id) ON DELETE SET NULL,
    external_id   TEXT NOT NULL DEFAULT '',
    created_at    TEXT NOT NULL,
    updated_at    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS applications (
    id            TEXT PRIMARY KEY,
    name          TEXT NOT NULL,
    secret        TEXT NOT NULL DEFAULT '',
    public        INTEGER NOT NULL DEFAULT 0,
    provider_id   TEXT REFERENCES providers(id) ON DELETE SET NULL,
    redirect_uris TEXT NOT NULL DEFAULT '[]',
    scopes        TEXT NOT NULL DEFAULT '',
    enabled       INTEGER NOT NULL DEFAULT 1,
    created_at    TEXT NOT NULL,
    updated_at    TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_users_provider ON users(provider_id);
CREATE INDEX IF NOT EXISTS idx_apps_provider  ON applications(provider_id);

-- Runtime state: persisted so logins, codes, and tokens survive restarts.
CREATE TABLE IF NOT EXISTS auth_codes (
    code                  TEXT PRIMARY KEY,
    client_id             TEXT NOT NULL,
    redirect_uri          TEXT NOT NULL DEFAULT '',
    subject               TEXT NOT NULL,
    scopes                TEXT NOT NULL DEFAULT '',
    nonce                 TEXT NOT NULL DEFAULT '',
    code_challenge        TEXT NOT NULL DEFAULT '',
    code_challenge_method TEXT NOT NULL DEFAULT '',
    auth_time             TEXT NOT NULL,
    expires_at            TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS access_tokens (
    token      TEXT PRIMARY KEY,
    jti        TEXT NOT NULL,
    client_id  TEXT NOT NULL,
    subject    TEXT NOT NULL,
    scopes     TEXT NOT NULL DEFAULT '',
    expires_at TEXT NOT NULL,
    revoked    INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    token      TEXT PRIMARY KEY,
    client_id  TEXT NOT NULL,
    subject    TEXT NOT NULL,
    scopes     TEXT NOT NULL DEFAULT '',
    expires_at TEXT NOT NULL,
    revoked    INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS sessions (
    id         TEXT PRIMARY KEY,
    subject    TEXT NOT NULL,
    expires_at TEXT NOT NULL
);

-- Remembered consent decisions per user + application.
CREATE TABLE IF NOT EXISTS grants (
    id         %[1]s,
    subject    TEXT NOT NULL,
    client_id  TEXT NOT NULL,
    scopes     TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(subject, client_id)
);

-- JWT signing keys. Exactly one row is active (used for signing); the rest
-- stay published in JWKS so outstanding tokens keep verifying.
CREATE TABLE IF NOT EXISTS signing_keys (
    kid        TEXT PRIMARY KEY,
    pem_enc    TEXT NOT NULL,
    active     INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    retired_at TEXT NOT NULL DEFAULT ''
);

-- External identities linked to a local user (account linking).
CREATE TABLE IF NOT EXISTS identities (
    id          %[1]s,
    user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider_id TEXT NOT NULL,
    external_id TEXT NOT NULL,
    created_at  TEXT NOT NULL,
    UNIQUE(provider_id, external_id)
);

CREATE TABLE IF NOT EXISTS audit_log (
    id        %[1]s,
    at        TEXT NOT NULL,
    event     TEXT NOT NULL,
    subject   TEXT NOT NULL DEFAULT '',
    client_id TEXT NOT NULL DEFAULT '',
    ip        TEXT NOT NULL DEFAULT '',
    detail    TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_audit_at ON audit_log(at);

-- RFC 8628 device authorization grant.
CREATE TABLE IF NOT EXISTS device_codes (
    device_code    TEXT PRIMARY KEY,
    user_code      TEXT NOT NULL UNIQUE,
    client_id      TEXT NOT NULL,
    scopes         TEXT NOT NULL DEFAULT '',
    status         TEXT NOT NULL DEFAULT 'pending',
    subject        TEXT NOT NULL DEFAULT '',
    interval_secs  INTEGER NOT NULL DEFAULT 5,
    last_polled_at TEXT NOT NULL DEFAULT '',
    expires_at     TEXT NOT NULL,
    created_at     TEXT NOT NULL
);

-- Groups/roles, mapped into the "groups" claim for clients that request it
-- (e.g. Portainer's OAuth team auto-assignment).
CREATE TABLE IF NOT EXISTS groups (
    id          %[1]s,
    name        TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL DEFAULT '',
    created_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS group_members (
    group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    user_id  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (group_id, user_id)
);

-- Single-use, expiring tokens for the forgot-password flow.
CREATE TABLE IF NOT EXISTS password_resets (
    token      TEXT PRIMARY KEY,
    subject    TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    created_at TEXT NOT NULL
);

-- Single-use, expiring tokens for confirming an email address.
CREATE TABLE IF NOT EXISTS email_verifications (
    token      TEXT PRIMARY KEY,
    subject    TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    created_at TEXT NOT NULL
);

-- WebAuthn/passkey credentials (FIDO2 / WebAuthn Level 2). One user may
-- register several (phone, security key, laptop TPM, ...). credential_json
-- is the go-webauthn library's own Credential struct, serialized whole —
-- storing it verbatim (rather than picking individual fields into columns)
-- means library upgrades that add fields to that struct don't require a
-- schema migration here.
CREATE TABLE IF NOT EXISTS webauthn_credentials (
    id              TEXT PRIMARY KEY, -- base64url credential ID
    user_id         INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name            TEXT NOT NULL DEFAULT '',
    credential_json TEXT NOT NULL,
    created_at      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_webauthn_user ON webauthn_credentials(user_id);
`, autoIncPK(d))
}

// columnMigrations add columns introduced after their table first shipped.
// Both backends support `ALTER TABLE t ADD COLUMN c ...` with this syntax,
// so the DDL text itself needs no per-dialect branching.
var columnMigrations = []struct{ table, column, ddl string }{
	{"users", "is_admin", `ALTER TABLE users ADD COLUMN is_admin INTEGER NOT NULL DEFAULT 0`},
	{"users", "failed_logins", `ALTER TABLE users ADD COLUMN failed_logins INTEGER NOT NULL DEFAULT 0`},
	{"users", "locked_until", `ALTER TABLE users ADD COLUMN locked_until TEXT NOT NULL DEFAULT ''`},
	{"users", "totp_secret", `ALTER TABLE users ADD COLUMN totp_secret TEXT NOT NULL DEFAULT ''`},
	{"users", "totp_enabled", `ALTER TABLE users ADD COLUMN totp_enabled INTEGER NOT NULL DEFAULT 0`},
	{"refresh_tokens", "family", `ALTER TABLE refresh_tokens ADD COLUMN family TEXT NOT NULL DEFAULT ''`},
	{"access_tokens", "audiences", `ALTER TABLE access_tokens ADD COLUMN audiences TEXT NOT NULL DEFAULT ''`},
	{"access_tokens", "jkt", `ALTER TABLE access_tokens ADD COLUMN jkt TEXT NOT NULL DEFAULT ''`},
	{"applications", "id_token_enc_key", `ALTER TABLE applications ADD COLUMN id_token_enc_key TEXT NOT NULL DEFAULT ''`},
	{"applications", "backchannel_logout_uri", `ALTER TABLE applications ADD COLUMN backchannel_logout_uri TEXT NOT NULL DEFAULT ''`},
	{"applications", "frontchannel_logout_uri", `ALTER TABLE applications ADD COLUMN frontchannel_logout_uri TEXT NOT NULL DEFAULT ''`},
	{"sessions", "created_at", `ALTER TABLE sessions ADD COLUMN created_at TEXT NOT NULL DEFAULT ''`},
	{"sessions", "user_agent", `ALTER TABLE sessions ADD COLUMN user_agent TEXT NOT NULL DEFAULT ''`},
	{"users", "email_verified", `ALTER TABLE users ADD COLUMN email_verified INTEGER NOT NULL DEFAULT 0`},
}
